### ISSUE TITLE
Where is the original recording?

### ISSUE THREAD

**Issue by vinayak-mehta** [rhcarvalho/The-Importance-of-Programming-Literacy#1]
Hi @rhcarvalho! Thank you for posting this. I was wondering if the original recording still exists? It would be awesome if you can point me to it! Thanks.

**Comment by rhcarvalho** [comment]
Hi! I'm afraid the official content might be unavailable.

https://pycon.blogspot.com/2007/03/status-of-pycon-videoaudio.html
https://pycon.blogspot.com/2007/03/keynote-slides-from-robert-m-lefkowitz.html

What did you intend to do with the material? Perhaps PyCon organizers could have access to it? I don't know.

**Comment by vinayak-mehta** [comment]
Yep I found the same blog posts but the audio links were broken.

> What did you intend to do with the material? Perhaps PyCon organizers could have access to it? I don't know.

I just wanted to listen to it since r0ml mentioned it in another talk. I also found some blogs that praised it a lot. I guess I'll just use the text :)

Thank you for transcribing the talk!

**Comment by rhcarvalho** [comment]
> r0ml mentioned it in another talk

Do you have a link to that one? :)

> Thank you for transcribing the talk!

I am happy this repo/transcript has been of use to someone, but I cannot take the credit for the transcription. I think I've only made minor fixes and stored it in a place that is still accessible today.

**Comment by vinayak-mehta** [comment]
> Do you have a link to that one? :)

Yes! He mentions it in his North Bay Python 2018 keynote at 19:20 (a few seconds after that) - https://youtu.be/h5fmhYc4U-Y?t=1160

> I am happy this repo/transcript has been of use to someone, but I cannot take the credit for the transcription. I think I've only made minor fixes and stored it in a place that is still accessible today.

Thank you for doing that!
